version: 2

sources:
  - name: telegram_data
    schema: public  # Replace with the schema where your table resides
    tables:
      - name: cleaned_data
        tests:
          - not_null:
              column_name: Channel
          - unique:
              column_name: Channel

